spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/rapido_upgrade
spring.datasource.username=root
spring.datasource.password=Spandan@2323

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
